In [7]:
import numpy as np
np.random.seed(10)

In [11]:
L=2
M=3
N=2

A=np.random.randint(low=0,high=15,size=(L,M))
B=np.random.randint(low=0,high=15,size=(M,N))
C=np.zeros((L,N),dtype=int)

In [15]:
A,B,C

(array([[ 6,  4,  3],
        [ 0,  4, 11]]),
 array([[ 6,  8],
        [11, 10],
        [14,  1]]),
 array([[0, 0],
        [0, 0]]))

In [14]:
np.matmul(A,B)

array([[122,  91],
       [198,  51]])

In [33]:
def arrayToDataMemory(A):
    a_=A.flatten()
    return '\n'.join(map(str,a_.tolist()))

def arraysToDataMemory(arrays):
    out=''
    for A in arrays:
        x,y = A.shape
        a_=A.flatten()
        out+='\n'.join(map(str,a_.tolist()))+'\n'

    return out


In [35]:
print(arraysToDataMemory([A,B,C]))

6
4
3
0
4
11
6
8
11
10
14
1
0
0
0
0



In [23]:
A

array([[ 6,  4,  3],
       [ 0,  4, 11]])

'6\n4\n3\n0\n4\n11'

In [27]:
def arrayToDataMemory(A):
    a_=A.flatten()
    return '\n'.join(map(str,a_.tolist()))

In [28]:
arrayToDataMemory(B)

'6\n8\n11\n10\n14\n1'